### ISSUE TITLE
Fetching inclusion rule statistics error

### ISSUE THREAD

**Issue by gowthamrao** [ohdsi-studies/Covid19CohortEvaluation#1]
Error on fetching inclusion rule statistics. 

```
Fetching inclusion rule statistics
- Fetching inclusion rule statistics for cohort sarilumab
Fetching inclusion statistics for cohort with cohort_definition_id = 14814
Error in bitwAnd(inclusionResults$inclusionRuleMask, mask) : 
  'a' and 'b' must have the same type
```

Details to follow. tagging @anthonysena

**Comment by gowthamrao** [comment]
Worked with @anthonysena - etl issue. Closing issue

**Comment by schuemie** [comment]
Did you figure out what the problem was? Could you share the solution here?

**Comment by gowthamrao** [comment]
In a datasource concept.invalid_reason field was populated with empty string vs expected NULL. This caused creation of empty codeset and cohort tables.  

The script ran without any warnings/error till it started reading local csv files with inclusion-rule-results. The csv file that contained inclusionRuleMask field only had one row (only header values). All other inclusion rule csv had more than one row for each combination of cohort/mode_id/inclusion-rule, with integer values of 0 populated, except for one csv that contained inclusionRuleMask field. Maybe bitwAnd(inclusionResults$inclusionRuleMask, mask) was returning an error because inclusionResults df had 0 rows and inclusionResults$inclusionRuleMask is NULL.

To think about: in this case zero person cohorts were created because of concept table ETL issue. What if a cohort definition creates a zero person cohort in a data source because there was really no persons that met the criteria. Will inclusionResults$inclusionRuleMask be NULL in that case and bitwAND throw an error? Should we check cohortCounts before reading the csv with inclusionRule data?
